### ISSUE TITLE
Why not use simple HTML and javascript instead of XUL?

### ISSUE THREAD

**Issue by juzerali** [CSSCorp/hybridfox#1]
That way it can be ported to other browsers as well including Chrome, Opera, Safari etc.

**Comment by anandof28** [comment]
@juzerali  The Add-on structure across browsers are not common, we need to develop them as a each stand alone Add-on, But right now we are into developing Firefox add-on with most part of HTML with Twitter Bootstrap into it rather than XUL

**Comment by juzerali** [comment]
Thats great. Isn't the html one hosted on github? Can I have a look at and possibly contribute to that?

**Comment by anandof28** [comment]
Thanks, ya it ll be under new branch hfx-1.8 once initial commit was done , i ll notify you @juzerali
